# for this repository azure can't running well on their VMImage (Windows Server 2019)
# it can be run with manually run as admin in any version of windows

trigger:

pool:
  vmImage: 'windows-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: BatchScript@1
  inputs:
    filename: 'Installation.bat'
  displayName: 'Batch'

- script: |
    python -m pip install --upgrade pip
  displayName: 'Install dependencies'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'ATOWU.py'
  displayName: 'pytest'

